softwaredelta/GNP

dev.ps1

* Changed docker run command as to read multiple ports
* Changed Set-Location path to the script execution path with $MyInvocation.MyCommand.Definition

[INFRA] Fixed ports and Set-Location path

---

.github/workflows/sonarcloud.yml

[INFRA] Added Sonarcloud pipeline

---

.github/workflows/sonarcloud.yml

[INFRA] Added main branch to sonarcloud list

---

ram-front/src/App.tsx
ram-front/src/components/button.tsx

This commit is an example that may serve as a base for all following components.

[FRONT]: Add example component

---

ram-front/index.html
ram-front/src/components/generics/Examples.tsx
ram-front/src/components/generics/alerts/Alert.tsx
ram-front/src/components/generics/skeleton/SkeletonCard.tsx
ram-front/src/components/generics/skeleton/SkeletonDiv.tsx
ram-front/src/components/generics/skeleton/SkeletonText.tsx
ram-front/src/hooks/useAlert.ts

More components

---

ram-back/package.json
ram-back/src/__tests__/arch.test.ts
ram-back/src/__tests__/user.test.ts
ram-back/src/__tests__/util.test.ts
ram-back/src/app/auth.ts
ram-back/src/app/user.ts
ram-back/src/entities/user.entity.ts
ram-back/src/utils/hash.ts
ram-back/yarn.lock

[Auth] Stop storing passwords in plain text #44

28 m3 s01todosiniciar sesión

---

ram-front/src/components/generics/Examples.tsx
ram-front/src/components/generics/alerts/Alert.tsx
ram-front/src/hooks/useAlert.ts
ram-front/src/pages/Home.tsx
ram-front/src/pages/InfraTest.tsx
ram-front/src/pages/Login.tsx
ram-front/src/pages/index.tsx
ram-front/src/recoil/visual/atoms.ts
ram-front/src/recoil/visual/index.ts
ram-front/src/recoil/visual/selectors.ts
ram-front/src/routes/privates.ts
ram-front/src/routes/public.ts
ram-front/src/types/index.ts

Add list routes and fix alert

---

ram-back/src/controller/group.ts
ram-back/src/controller/routes.ts
ram-back/src/seeds/index.ts
ram-front/package.json
ram-front/src/components/generics/cards/info/CardInfoNumMembers.tsx
ram-front/src/lib/api/api-courses.ts
ram-front/src/pages/Home.tsx
ram-front/src/pages/ManagerCourses.tsx
ram-front/src/pages/index.tsx

34 m1 s04gerentever cursos y número de agentes por grupo

---

ram-back/package.json
ram-back/src/__tests__/groups.test.ts
ram-back/src/app/deliveries.ts
ram-back/src/app/groups.ts
ram-back/src/controller/group.ts
ram-back/src/controller/routes.ts
ram-back/src/entities/delivery.entity.ts
ram-back/src/entities/group.entity.ts
ram-back/src/entities/user-delivery.ts
ram-back/src/seeds/index.ts
ram-back/yarn.lock
ram-front/src/components/groups/ListGroup.tsx
ram-front/src/pages/Groups.tsx
ram-front/src/pages/Home.tsx
ram-front/src/routes/privates.ts
ram-front/src/routes/public.ts

40 m1 s01agentever mis grupos y mi avance en cada uno

---

ram-back/src/__tests__/app/sale.test.ts
ram-back/src/__tests__/controller/sale.test.ts
ram-back/src/app/sale.ts
ram-back/src/controller/sale.ts
ram-back/src/seeds/index.ts
ram-front/src/pages/Home.tsx
ram-front/src/routes/privates.ts

[Fix] POST for NewSale was fixed

---

ram-front/src/components/includes/NavBar/NavBar.tsx
ram-front/src/components/sales/CardNewSale.tsx

[FRONT] Navbar links

---

ram-back/.eslintrc
ram-back/eslint-plugin-gnp-linter/index.js
ram-back/eslint-plugin-gnp-linter/package.json
ram-back/package.json
ram-back/src/__tests__/app/deliveries.test.ts
ram-back/src/__tests__/controller/deliveries.test.ts
ram-back/src/app/deliveries.ts
ram-back/src/app/groups.ts
ram-back/src/entities/assurance-type.entity.ts
ram-back/src/entities/columns.ts
ram-back/src/entities/delivery.entity.ts
ram-back/src/entities/goal.entity.ts
ram-back/src/entities/group-user.entity.ts
ram-back/src/entities/index.ts
ram-back/src/entities/user-delivery.entity.ts
ram-back/src/seeds/index.ts
ram-back/yarn.lock

**Problem**
We only want to use features available in both sqlite and postgress
**Solution**
New linter checks for correctly configured column options and type definitions

[Infra] Add linter to make sure db is configured correctly

---

ram-back/package.json
ram-back/src/seeds/index.ts
ram-back/yarn.lock
ram-front/src/__test__/managerCourses.test.tsx
ram-front/src/__test__/managerDeliveries.test.tsx
ram-front/src/components/deliverables/ListManagerDeliveries.tsx
ram-front/src/components/generics/cards/info/ManagerDelivery.tsx
ram-front/src/components/groups/ListManagerGroup.tsx
ram-front/src/pages/GroupDeliveries.tsx
ram-front/src/pages/ManagerCourses.tsx

76 m1 s04 missing frontend test

---

ram-front/src/App.tsx
ram-front/src/lib/api/api-auth.tsx

avoid redirects to home page on refresh

[Auth] Fix auth init loading

---

ram-back/src/app/sale.ts
ram-front/src/components/sales/VerifySalesRow.tsx
ram-front/src/components/sales/VerifySalesTable.tsx

[FRONT] See file

---

ram-back/src/__tests__/app/sale.test.ts
ram-back/src/__tests__/controller/sale.test.ts
ram-back/src/app/sale.ts
ram-back/src/controller/sale.ts
ram-back/src/seeds/index.ts
ram-front/src/components/sales/CardNewSale.tsx

[Fix] Add post sales

---

ram-back/src/__tests__/controller/delivery.test.ts
ram-back/src/app/deliveries.ts
ram-back/src/controller/delivery.ts
ram-back/src/controller/sale.ts
ram-back/src/seeds/index.ts
ram-front/src/__test__/ManagerListGroupDeliveries.test.tsx
ram-front/src/__test__/managerDeliveries.test.tsx
ram-front/src/components/deliverables/UserDeliveriesTable.tsx
ram-front/src/components/deliverables/UserDeliveryRow.tsx
ram-front/src/pages/ManagerDelivery.tsx
ram-front/src/types/index.ts

105 verify delivery

---

ram-back/src/__tests__/app/groups.test.ts
ram-back/src/app/groups.ts

[M1_S10] Delete groups function

---

ram-back/src/seeds/index.ts
ram-front/src/components/deliverables/UserDeliveriesTable.tsx
ram-front/src/components/deliverables/UserDeliveryRow.tsx
ram-front/src/pages/ManagerDelivery.tsx

113 stable client version

---

ram-back/src/__tests__/app/groups.test.ts
ram-back/src/__tests__/controller/groups.test.ts
ram-back/src/app/groups.ts
ram-back/src/arch/s3-client.ts
ram-back/src/controller/group.ts
ram-back/src/entities/group.entity.ts

**PR Data:**
Task ID: 100
Problem: We need an endpoint so users can create groups from the website
Solution: Adjust existing endpoint, to allow for image upload, also add tests for logic. Add small
update to s3 api.
Reviewer Name: Alejandro Martínez Luna 
If the submitter makes updates to the PR, you **MUST** …

[M1 S09 t100] Implement create group endpoint

---

ram-back/src/__tests__/app/groups.test.ts
ram-back/src/__tests__/app/sale.test.ts
ram-back/src/__tests__/controller/groups.test.ts
ram-back/src/__tests__/controller/sale.test.ts
ram-back/src/app/groups.ts
ram-back/src/app/sale.ts
ram-back/src/arch/s3-client.ts
ram-back/src/controller/group.ts
ram-back/src/controller/sale.ts
ram-back/src/entities/group.entity.ts
ram-back/src/seeds/index.ts

**PR Data:**
Task ID: 3470
Problem: Controller and function don't contemplate new sell entity columns
Solution: Changed params in controller, changed params middleware and app function to include paidFee, emissionDate and insuredCostumer fields.
Submitter Name: Mónica Ayala and Jordana Betancourt
Reviewer Name:
If the submitter makes …

[BACK] Changed controller and function

---

ram-back/.eslintrc
ram-back/src/__tests__/controller/deliveries.test.ts
ram-back/src/__tests__/controller/delivery.test.ts
ram-back/src/app/user-delivery.ts
ram-back/src/controller/files.ts
ram-back/src/seeds/index.ts
ram-front/.eslintrc
ram-front/src/components/Delivery.tsx
ram-front/src/components/deliverables/ListDeliverables.tsx
ram-front/src/components/sales/CardNewSale.tsx
ram-front/src/components/sales/SalesRow.tsx
ram-front/src/components/sales/VerifySalesRow.tsx
ram-front/src/components/sales/VerifySalesTable.tsx
ram-front/src/lib/api/api-auth.tsx
ram-front/src/pages/Group.tsx
ram-front/src/pages/SalesHistory.tsx
ram-front/src/pages/VerifySales.tsx
ram-front/src/routes/privates.tsx

**PR Data:**
Task ID: 6700
Problem: A lot of unused variables are left in the code.
Solution: Update linter so any unused variable is a strict error.

[Infra] Make linter stricter for unused variables

---

ram-back/src/__tests__/app/prospect.test.ts
ram-back/src/app/prospect.ts
ram-back/src/app/satus-prospect.ts
ram-back/src/app/status.ts
ram-back/src/entities/index.ts
ram-back/src/entities/prospect-status.entity.ts
ram-back/src/entities/prospect.entity.ts
ram-back/src/entities/status.entity.ts
ram-back/src/seeds/index.ts

**PR Data:**
Task ID: 4700
Problem: how add a prospect
Solution: function add prospect
Submitter Name: Ángel
Reviewer Name: Kenny

[BACK] function add prospect id4700

---

ram-back/src/__tests__/controller/sale.test.ts
ram-back/src/app/file.ts
ram-back/src/app/groups.ts
ram-back/src/controller/sale.ts
ram-back/src/controller/user-delivery.ts
ram-front/src/components/sales/CardNewSale.tsx

**PR Data:**
Task ID: 3500, 3600
Problem: Fields are missing in the register sale form including uploading a file.
Solution: The fields for sending documents and quarterly periodicity are added in the form, in addition to the endpoint to upload the file.
Submitter Name: Jordana Betancourt Menchaca and Mónica Ayala
Reviewer Name:
If the …

136 front add the missing fields to the sale registration form component id3600

---

ram-back/src/__tests__/controller/delivery.test.ts
ram-back/src/controller/delivery.ts

**PR Data:**
Task ID: 601
Problem: Create Delivery endpoint wasn´t handling the file upload with S3Api.
Solution: Added the functionality in the controller and added a test to make sure the endpoint works.
Submitter Name: 
Mónica Ayala
Reviewer Name: Jordana Betancourt Menchaca
If the submitter makes updates to the PR, you **MUST** go …

[BACK] Add fileupload to delivery controller

---

ram-back/src/controller/prospect.ts
ram-back/src/controller/routes.ts

**PR Data:**
Task ID: 4800
Problem: We need an endpoint to create a new prospect
Solution: Add an endpoint to create a new prospect
Submitter Name: Diego Emilio and Angel Rico
If you make changes to the PR, you **HAVE** to make sure all steps are still true.
Reviewer Name:

[BACK] Add prospect endpoint

---

ram-front/src/__test__/searchAgentTable.test.tsx
ram-front/src/__test__/searchDeliveryTable.test.tsx
ram-front/src/components/tables/SearchAgentRow.tsx
ram-front/src/components/tables/SearchAgentTable.tsx
ram-front/src/components/tables/SearchDeliveryRow.tsx
ram-front/src/components/tables/SearchDeliveryTable.tsx
ram-front/src/pages/Examples.tsx
ram-front/src/types/index.ts

**PR Data:**
Task ID: 1102
Problem: Component for a searching table for agents and deliveries don´t exist
Solution: Added a component for a  searching table, this shoud help in the front end for M1_S09, M1_S10
Reviewer Name:
If the submitter makes updates to the PR, you **MUST** go through all …

M1 s10 tablas grupos

---

ram-back/src/__tests__/app/deliveries.test.ts
ram-back/src/app/deliveries.ts

**PR Data:**
Task ID: 3000
Problem: We don't have a way of deleting deliveries
Solution: Create new function with associated tests

[M1_S12_3000] Function to delete delivery

---

ram-front/src/assets/css/index.css
ram-front/src/components/forms/ModalDeliveryForm.tsx
ram-front/src/pages/EditGroup.tsx
ram-front/src/pages/Examples.tsx

**PR Data:**
Task ID: 1901
Problem: No validation errors were shown when creating a deliverable.
Solution: Name and file validations are added, as well as a successful deliverable creation alert
Submitter Name: Jordana Betancourt
If the submitter makes updates to the PR, you **MUST** go through all …

158 front show validation errors in the create deliverable form

---

ram-back/src/__tests__/app/prospect.test.ts
ram-back/src/app/status.ts
ram-back/src/controller/routes.ts
ram-back/src/controller/sale.ts
ram-back/src/controller/status.ts
ram-back/src/entities/status.entity.ts
ram-back/src/seeds/index.ts
ram-front/index.html
ram-front/src/__test__/modalProspectForm.test.tsx
ram-front/src/assets/css/index.css
ram-front/src/components/deliverables/ListDeliverables.tsx
ram-front/src/components/forms/ModalProspectForm.tsx
ram-front/src/pages/Prospects.tsx
ram-front/src/types/index.ts
ram-front/tailwind.config.cjs

**PR Data:**
Task ID: 5100
Problem: We haven't  conection FRONT and BACK for add prospect
Solution:  Add conection FRONT and BACK for add prospect
Reviewer Name:

[FRONT] Add conection FRONT and BACK for add prospect

---

ram-back/src/__tests__/app/groups.test.ts
ram-back/src/app/groups.ts

**PR Data:**
Task ID: 800
Problem: New function to update a group
Solution:Implement the funciton
Submitter Name: Fermín
Reviewer Name: Kenny

120 m1 s10administradormodificar o borrar un grupo de entregables

---

ram-front/src/__test__/managerCourses.test.tsx
ram-front/src/components/generics/cards/info/CardInfoNumMembers.tsx
ram-front/src/components/groups/ManagerListGroups.tsx
ram-front/src/lib/api/api-courses.ts
ram-front/src/pages/ManagerGroups.tsx

**PR Data:**
Task ID: 700, 701
Problem: No connection to front end of delete group
Solution: The button was connected in the UI to delete a group, showing a confirmation popup
Reviewer Name: Kenny

[FRONT] Added connection for delete group

---

ram-back/src/__tests__/controller/deliveries.test.ts
ram-back/src/controller/delivery.ts

**PR Data:**
Task ID: 3100
Problem: No way to delete delivery from web site
Solution: Add new endpoint to delete deliveries from website
Reviewer Name:

[M1 S12] Add endpoint to delete delivery

---

ram-back/src/__tests__/app/deliveries.test.ts
ram-back/src/app/deliveries.ts

**PR Data:**
Task ID: 2500
Problem: There is no function to update deliveries
Solution: Create new function that updates name, description, or image url
Reviewer Name:

[M1 S12] Add update delivery function

---

ram-back/src/__tests__/app/deliveries.test.ts
ram-back/src/__tests__/controller/delivery.test.ts
ram-back/src/app/deliveries.ts
ram-back/src/controller/delivery.ts

**PR Data:**
Task ID: 2600
Problem: We don't have a way to update delivery data from the website
Solution: Create the new endpoint to modify deliveries
Reviewer Name: Jordana Betancourt

[M1 S12] Add new endpoint to modify delivery

---

ram-front/src/components/tables/SearchDeliveryRow.tsx

**PR Data:**
Task ID: fix-0001
Problem: The image url wasn't created properly
Solution: Use existing hook to properly display image
Reviewer Name:

Fix image url for deliveries table

---

ram-front/src/components/includes/NavBar/NavBar.tsx

**PR Data:**
Task ID: fix-0002
Problem: The links in the navbar don't show as active when they should
Solution: Set links to active based on current active location
Reviewer Name:

Show active link in navbar

---

ram-back/src/__tests__/app/sale.test.ts
ram-back/src/app/sale.ts

**PR Data:**
Task ID: 3800
Problem: Missing function for updating sales
Solution: Added function and tests 
Submitter Name: Jordana Betancourt, Halim Abraham y Mónica Ayala

M1 s12 2600 modify delivery endpoint

---

ram-back/src/app/groups.ts
ram-back/src/controller/group.ts
ram-front/src/__test__/searchAgentTable.test.tsx
ram-front/src/components/tables/SearchAgentRow.tsx
ram-front/src/components/tables/SearchAgentTable.tsx
ram-front/src/pages/EditGroup.tsx
ram-front/src/pages/Examples.tsx

**PR Data:**
Task ID: 7200
Problem: There is no way to remove users from a group
Solution: Connect the button to a new endpoint to remove agents
Reviewer Name:

[M1 S10] Remove user from group

---

ram-front/src/components/agent/AgentFuzzyFinder.tsx
ram-front/src/pages/EditGroup.tsx

**PR Data:**
Task ID: 7300
Problem: The agent add table looks bad
Solution: Add some initial tailwind
Reviewer Name:

[M1 S10] Give some initial style to add agent table

---

ram-front/src/__test__/listGroups.test.tsx
ram-front/src/components/groups/ListGroup.tsx

**PR Data:**
Task ID: fix-0003
Problem: Se usaba un url incorrecto
Solution: Usar el hook para tener el url correcto
Reviewer Name: Alejandro Martínez 

Use correct image url for group images

---

ram-front/src/components/groups/ManagerListGroups.tsx

**PR Data:**
Task ID: 7400
Problem: No se usa el url correcto
Solution: Utilizar hook para urls

Use correct url for group image

---

ram-back/src/__tests__/controller/user.test.ts
ram-back/src/app/file.ts
ram-back/src/app/log.ts
ram-back/src/arch/db-client.ts
ram-back/src/arch/instance.ts
ram-back/src/controller/index.ts
ram-back/src/controller/infra.ts
ram-back/src/controller/user.ts
ram-back/src/entities/index.ts
ram-back/src/entities/log.entity.ts
ram-back/src/entities/user.entity.ts
ram-back/src/seeds/index.ts
ram-infra/aws.yml

**PR Data:**
Task ID: 7000
Problem: Necesitamos comprobar que el sistema funciona en AWS
Solution: Probar base de datos, archivos, pagina, etc.
Reviewer Name:

[Infra] Fix aws deployment, db, s3, etc.

---

ram-front/src/pages/ManagerGroups.tsx

**PR Data:**
Task ID: 400
Problem: Redirect to the edit group page once you  create a new group
Solution: added a navigate to group/edit/:id page
Submitter Name: Alfredo
Reviewer Name: Kenny

[FRONT] redirect to edit group

---

ram-back/src/controller/sale.ts
ram-front/src/components/sales/CardModifySale.tsx
ram-front/src/components/sales/SalesRow.tsx
ram-front/src/lib/api/api-sales.ts
ram-front/src/pages/ModifySale.tsx
ram-front/src/routes/privates.tsx
ram-front/src/types/index.ts

Co-authored-by: JordanaBM <JordanaBM@users.noreply.github.com>
**PR Data:**
Task ID: 4000
Problem: Missing page for editing sale
Solution: Added edit button to redirect to card for editing sale
Submitter Name: Mónica Ayala and Jordana Betancourt
Reviewer Name: Alejandro Martínez Luna 
If the submitter makes updates to the PR, you …

[FRONT] New page and component for modify sale

---

ram-back/src/app/user.ts
ram-back/src/controller/user.ts
ram-back/src/entities/user.entity.ts
ram-front/src/assets/css/index.css
ram-front/src/components/agent/AgentFuzzyFinder.tsx
ram-front/src/components/forms/UserForm.tsx
ram-front/src/components/includes/NavBar/NavBar.tsx
ram-front/src/components/prospects/FunnelTable.tsx
ram-front/src/components/tables/SearchAgentTable.tsx
ram-front/src/hooks/useAxios.ts
ram-front/src/pages/AddUser.tsx
ram-front/src/routes/privates.tsx
ram-front/src/types/index.ts

[FRONT][BACK] Add user

---

ram-front/src/components/auth/LoginForm.tsx

[FRONT] Login style

---

ram-back/src/app/deliveries.ts
ram-back/src/app/user-delivery.ts
ram-back/src/controller/delivery.ts
ram-back/src/controller/group.ts

**PR Data:**
Task ID: 1405
Problem: Users in group couldn´t see their deliveries
Solution: Added functions "setUserToAllDeliveries" and "setDeliveryToAllUsers" when adding users or deliveries to a group. 
Submitter Name: Mónica Ayala
Reviewer Name:

207 back deliveries in groups arent shown to users

---

ram-front/src/__test__/searchDeliveryTable.test.tsx
ram-front/src/components/tables/SearchAgentTable.tsx
ram-front/src/components/tables/SearchDeliveryRow.tsx
ram-front/src/components/tables/SearchDeliveryTable.tsx
ram-front/src/pages/EditGroup.tsx
ram-front/src/pages/Examples.tsx

**PR Data:**
Task ID: 1902
Problem: When you added a delivery, the data update was not reflected
Solution: Put an updateData inside the useAxios and now the new data is seen in the front
Submitter Name: Jordana Betancourt
Reviewer Name: Alfredo

[FRONT] Added re render when add or delete a delivery

---

ram-back/src/controller/sale.ts
ram-front/src/pages/Prospects.tsx

**PR Data:**
Task ID: 7800
Problem: Fix bug
Solution: Fix bug
Submitter Name: Angel
Reviewer Name:

[BACK][FRONT] Fix controller and view

---

ram-infra/aws.yml

fix aws version

---

ram-infra/aws.yml

set admin password in aws template

---

ram-back/src/seeds/index.ts
ram-front/src/components/prospects/FunnelRow.tsx
ram-front/src/components/prospects/FunnelTable.tsx

**PR Data:**
Task ID: 7900
Problem: Seeds weren´t clean for client
Solution: Changed seeds for client and testing purpose
Submitter Name: Mónica Ayala and Alex Luna
Reviewer Name:

[BACK] Change seeds

---

ram-front/src/components/forms/ModalDeliveryFormUpdate.tsx
ram-front/src/components/tables/SearchDeliveryRow.tsx
ram-front/src/pages/EditGroup.tsx

Resolved initialValues on EditDelivery

---

ram-back/src/__tests__/controller/user.test.ts
ram-back/src/controller/user.ts
ram-back/src/seeds/index.ts
ram-front/src/components/prospects/FunnelRow.tsx
ram-front/src/components/prospects/FunnelTable.tsx
ram-front/src/components/prospects/ListProspects.tsx
ram-front/src/components/tables/SearchAgentRow.tsx
ram-front/src/components/tables/SearchAgentTable.tsx
ram-front/src/components/tables/SearchDeliveryRow.tsx
ram-front/src/components/tables/SearchDeliveryTable.tsx
ram-front/src/hooks/useSearch.ts
ram-front/src/pages/EditGroup.tsx
ram-front/src/pages/Prospects.tsx

**PR Data:**
Task ID: M5_S02 & M5_S08
Problem: There was no filter for prospects
Solution: Added a useSearchHook to filter names
Reviewer Name:

233 front hook for search filter

---

ram-front/src/components/includes/NavBar/NavBar.tsx
ram-front/src/components/members/RowMember.tsx
ram-front/src/components/members/TableMembers.tsx
ram-front/src/pages/Members.tsx
ram-front/src/routes/privates.tsx
ram-front/src/types/index.ts

**PR Data:**
Task ID: 2108
Problem: There isn't a page for showing all members and connecting buttons for edition, adding new member, seeing data from them
Solution: Added members page and navbar redirection
Submitter Name: Fermin M
Reviewer Name:

230 front new page members

---

ram-front/src/components/prospects/ProspectListHistory.tsx
ram-front/src/pages/Examples.tsx
ram-front/src/pages/ProspectsHistory.tsx
ram-front/src/routes/privates.tsx

**PR Data:**
Task ID: 6690, 6700
Problem: Add Front History Prospect 
Submitter Name: Renato Ramirez
Reviewer Name: Alfredo

[FRONT]Add  front ProspectHistory ProspectListHistory

---

ram-back/src/__tests__/app/user.test.ts
ram-back/src/__tests__/controller/user.test.ts
ram-back/src/app/user.ts
ram-back/src/entities/columns.ts
ram-back/src/entities/user.entity.ts

**PR Data:**
Task ID: 236
Problem: New function get all users and roles
Solution: Implement function
Reviewer Name:

236 back function get all members information

---

ram-back/src/app/user.ts
ram-back/src/controller/user.ts
ram-back/src/entities/columns.ts
ram-back/src/entities/user.entity.ts
ram-front/src/components/forms/ModalAddUser.tsx
ram-front/src/types/index.ts

[FRONT] Added New Modal for creating users

---

ram-front/src/components/members/RowMember.tsx
ram-front/src/components/members/TableMembers.tsx
ram-front/src/pages/Members.tsx
ram-front/src/types/index.ts

**PR Data:**
Task ID: 2109
Problem: 
Solution: Connect member page and endpoint
Submitter Name: Fermin
Reviewer Name:

257 frontback connect members endpoint and page

---

ram-back/src/app/deliveries.ts
ram-back/src/controller/delivery.ts
ram-front/src/components/deliverables/LinkDelivery.tsx
ram-front/src/components/deliverables/ListManagerDeliveries.tsx
ram-front/src/components/members/RowMember.tsx
ram-front/src/components/members/TableMembers.tsx
ram-front/src/pages/DeliveryGroup.tsx
ram-front/src/pages/Groups.tsx
ram-front/src/pages/ManagerGroup.tsx
ram-front/src/pages/Members.tsx
ram-front/src/types/index.ts

**PR Data:**
Task ID: 1908 y 1909
Problem: No estaba conectada la página de miembros con la funcionalidad de agregar usuario
Solution: Se conectó el modal con la página 
Reviewer Name:

[FRONT] Modified Page Memebers for adding user

---

ram-front/src/__test__/ProspectsHistory.test.tsx
ram-front/src/components/prospects/ProspectHistoryTable.tsx
ram-front/src/components/prospects/ProspectListHistory.tsx
ram-front/src/pages/Examples.tsx
ram-front/src/pages/ProspectsHistory.tsx

**PR Data:**
Task ID:6671
Problem: Add test to front page prospect history
Submitter Name: Renato Ramirez
Reviewer Name: Alfredo

247 front add tests prospect history

---

ram-back/src/controller/user.ts
ram-front/src/assets/css/index.css
ram-front/src/components/forms/ModalLinks.tsx
ram-front/src/components/forms/ModalPasswordReset.tsx
ram-front/src/components/forms/ProfileForm.tsx
ram-front/src/components/generics/cards/ProfileCard.tsx
ram-front/src/components/generics/lists/LinkList.tsx
ram-front/src/components/generics/lists/LinkRow.tsx
ram-front/src/components/includes/NavBar/NavBar.tsx
ram-front/src/components/members/RowMember.tsx
ram-front/src/pages/Profile.tsx
ram-front/src/routes/privates.tsx

**PR Data:**
Task ID: 5010, 5020, 5040
Problem: Missing page for edit profile and missing components.
Solution: Linked edit in member list to new profile page.
Files added:
Submitter Name: Mónica Ayala
Reviewer Name:

237 front new component for user profile

---

ram-back/src/app/prospect.ts
ram-back/src/app/user.ts
ram-back/src/controller/prospect.ts
ram-back/src/seeds/index.ts
ram-front/src/components/prospects/FunnelRow.tsx
ram-front/src/components/prospects/FunnelTable.tsx
ram-front/src/components/prospects/ListProspects.tsx
ram-front/src/components/prospects/RowProspect.tsx
ram-front/src/pages/ManageProspects.tsx
ram-front/src/pages/Prospects.tsx
ram-front/src/pages/ProspectsFunnel.tsx
ram-front/src/routes/privates.tsx
ram-front/src/types/index.ts

261 frontback view prospects

---

ram-back/src/__tests__/app/user.test.ts
ram-back/src/__tests__/controller/user.test.ts
ram-back/src/app/user.ts
ram-back/src/controller/user.ts
ram-back/src/entities/index.ts
ram-back/src/entities/user-link.entity.ts
ram-back/src/entities/user.entity.ts

**PR Data:**
Task ID: 5030, 5031, 5032, 5033
Problem: Missing backend to change a user's profile (reset password, add llink, delete link, modify link, change image, modify names)
Solution: Added multiple backend functions and model funcitons as well as user-link entity
Submitter Name: Mónica Ayala 
Reviewer Name:
If the submitter makes …

[BACK] New link-user entity

---

ram-back/src/app/deliveries.ts
ram-back/src/controller/delivery.ts
ram-back/src/entities/columns.ts
ram-back/src/entities/delivery.entity.ts
ram-front/src/components/deliverables/ListDeliverables.tsx
ram-front/src/components/forms/EditDeliveryForm.tsx
ram-front/src/components/generics/cards/DeliveryCard.tsx
ram-front/src/components/tables/SearchDeliveryRow.tsx
ram-front/src/pages/DeliveryGroup.tsx
ram-front/src/pages/ManagerDeliveryGroup.tsx
ram-front/src/routes/privates.tsx
ram-front/src/types/index.ts

**PR Data:**
Task ID: 14400
Problem: There was no page for manager to see deliverables with description
Solution: Added  manager page to view deliverables with description
Reviewer Name:

258 front back add delivery description view for manager

---

ram-front/src/__test__/deliveryDescription.test.tsx
ram-front/src/__test__/image.test.tsx
ram-front/src/components/Image.tsx
ram-front/src/components/deliverables/DeliveryDescription.tsx

**PR Data:**
Task ID: 14000
Problem: There was not test for front 
Solution: Created test for front
Submitter Name: Diego Emilio
Reviewer Name:

260 front test for delivery description

---

ram-back/src/__tests__/app/user.test.ts
ram-back/src/controller/user.ts
ram-front/src/components/forms/ProfileForm.tsx
ram-front/src/components/generics/lists/LinkList.tsx
ram-front/src/pages/Profile.tsx

**PR Data:**
Task ID:5041, 5050
Problem: Profile page for editing wasn´t connected to backend
Solution: Added connection to back end and success validation messages
Submitter Name: Mónica Ayala
Reviewer Name:

270 frontback edit profile and success message

---

ram-back/src/__tests__/app/links.test.ts
ram-back/src/__tests__/controller/prospect.test.tsx
ram-back/src/app/deliveries.ts
ram-back/src/controller/delivery.ts
ram-front/src/components/filters/DropdownFilter.tsx
ram-front/src/components/forms/EditDeliveryForm.tsx
ram-front/src/components/generics/lists/LinkDeliveryList.tsx
ram-front/src/pages/ManagerDeliveryGroup.tsx

**PR Data:**
Task ID: 14400. 14500,14600, 14700
Problem: Delete and edit links of a delivery did not work
Solution: Changed delivery links controller
Reviewer Name:

271 front add links to deliveries

---

ram-back/src/controller/prospect.ts
ram-front/src/components/forms/ModalModifyStatusProspect.tsx
ram-front/src/components/prospects/ListProspects.tsx
ram-front/src/components/prospects/RowProspect.tsx
ram-front/src/pages/Examples.tsx
ram-front/src/pages/ManageProspects.tsx
ram-front/src/pages/Prospects.tsx

**PR Data:**
Task ID: Defect log
Problem: when modifying or adding a prospectus it is not re rendered
Solution: Adding callback function when a post is made
Submitter Name: Jordana Betancourt
Reviewer Name:

281 front bug when modifying or adding a prospectus it is not re rendered

---

ram-back/src/__tests__/controller/user.test.ts
ram-back/src/app/user.ts
ram-back/src/controller/user.ts
ram-front/src/components/forms/ProfileForm.tsx
ram-front/src/components/generics/cards/ProfileCard.tsx
ram-front/src/components/generics/lists/LinkList.tsx
ram-front/src/components/generics/lists/LinkRow.tsx
ram-front/src/components/includes/NavBar/NavBar.tsx
ram-front/src/components/members/RowMember.tsx
ram-front/src/components/members/TableMembers.tsx
ram-front/src/components/prospects/FunnelRow.tsx
ram-front/src/components/prospects/FunnelTable.tsx
ram-front/src/pages/Members.tsx
ram-front/src/pages/MyProfile.tsx
ram-front/src/pages/Profile.tsx
ram-front/src/pages/ViewProfile.tsx
ram-front/src/routes/privates.tsx
ram-front/src/types/index.ts

**PR Data:**
Task ID: 20000, 4010, 4020, 4030.
Problem: Couldn´t see my profile, edit my profile or see the profiles of member as a Manager
Solution: Modified ProfileForm so it could be either "Edit" or "Not Edit" in which the conditional rendering allows you to see your profile.
Submitter Name:Mónica Ayala
Reviewer Name:
If the …

[FRONT][BACK] See profile, see my profile and member list

---

ram-back/src/controller/sale.ts
ram-front/src/__test__/verifySales.test.tsx
ram-front/src/components/sales/SalesRow.tsx
ram-front/src/components/sales/VerifySalesTable.tsx
ram-front/src/pages/VerifySales.tsx

Table tabs

---

ram-back/src/app/satus-prospect.ts
ram-back/src/controller/routes.ts
ram-back/src/controller/status-prospect.ts
ram-front/src/__test__/ProspectsHistory.test.tsx
ram-front/src/components/prospects/ListProspects.tsx
ram-front/src/components/prospects/ProspectHistoryTable.tsx
ram-front/src/components/prospects/ProspectListHistory.tsx
ram-front/src/components/prospects/RowProspect.tsx
ram-front/src/pages/Examples.tsx
ram-front/src/pages/ProspectsHistory.tsx
ram-front/src/routes/privates.tsx
ram-front/src/types/index.ts

**PR Data:**
Task ID: 6660 y 6670
Reviewer Name:

M5 s07 endpoint estados de prospectos

---

ram-back/src/controller/status-prospect.ts
ram-back/src/seeds/index.ts
ram-front/src/__test__/verifySales.test.tsx
ram-front/src/components/sales/VerifySalesRow.tsx
ram-front/src/components/sales/VerifySalesTable.tsx
ram-front/src/pages/Examples.tsx
ram-front/src/pages/VerifySales.tsx

**PR Data:**
Task ID: 1809
Problem: Manager view of verify sales didn´t have filters or total sums
Solution: Modified verify sales components using the code structure of Sales Table
Submitter Name: Mónica Ayala y Alfredo Huerta
Reviewer Name:

1808 add front filters to sales

---

README.md

[FRONT] Removed space

---

README.md

**PR Data:**
Problem: La instancia se cayó :c
Solution: Vamos a ver si se puede reiniciar c':
Reviewer Name:

New change on Readme

---

ram-front/src/components/generics/lists/LinkRow.tsx
ram-front/src/components/members/TableMembers.tsx
ram-front/src/pages/EditGroup.tsx
ram-front/src/pages/VerifySales.tsx

**PR Data:**
Task ID: N/A
Problem: Bug 70,81 y 83
Solution: Added wrap with title, alert and filter
Reviewer Name: Mónica Ayala

293 fix delivery link and prospect table

---

ram-front/src/components/forms/EditDeliveryForm.tsx
ram-front/src/components/forms/ModalDeliveryFormCreate.tsx
ram-front/src/components/prospects/ListProspects.tsx
ram-front/src/components/tables/SearchDeliveryRow.tsx
ram-front/src/pages/Members.tsx
ram-front/src/types/index.ts

**PR Data:**
Task ID: Bug 88,89,86,67
Problem: Bugs
Solution: Fixed bugs
Submitter Name: Jordana Betacnourt
Reviewer Name:

[FRONT] Fixed bugs from url image

---

ram-back/src/app/satus-prospect.ts
ram-front/src/components/generics/cards/ProfileCard.tsx

**PR Data:**
Defect ID: 93, 95
Problem: Bugs on defect log 
Solution: Fixed Bugs 
Submitter Name: Alejandro Martínez
Reviewer Name: Jordana Betancourt Menchaca

317 front in the user modification view regular and manager roles are set instead of agent and manager

---

ram-front/src/components/forms/SaleForm.tsx
ram-front/src/components/prospects/ListProspects.tsx
ram-front/src/components/prospects/ProspectListHistory.tsx
ram-front/src/components/prospects/RowProspect.tsx

**PR Data:**
Task ID: 
Problem: The view of History Prospect was not ✨aesthetic ✨
Solution: It still not ✨aesthetic ✨but it works 
Submitter Name: Alejandro Martínez
Reviewer Name: Jordana Betancourt Menchaca

Changes on prospect history

---

ram-front/src/components/forms/ProfileForm.tsx
ram-front/src/components/generics/lists/LinkList.tsx
ram-front/src/components/generics/lists/LinkRow.tsx
ram-front/src/components/prospects/FunnelRow.tsx
ram-front/src/components/prospects/FunnelTable.tsx

**PR Data:**
Defect ID: 46, 52, 53, 
Problem: Some bugs reported on the defect log 
Solution: Fixed Bugs  
Submitter Name: Alejandro Martínez 
Reviewer Name:

[FRONT] Fixes on Links, PP200 Button and Removed Console Logs

---

ram-back/src/controller/sale.ts

[BACK] Fixed controller for create sale

---

ram-back/src/__tests__/controller/user.test.ts
ram-back/src/app/user.ts

**PR Data:**
Task ID: 10005
Problem: Add auth validate if the user is active
Solution: Add auth validate if the user is active
Submitter Name: Angel Rico
Reviewer Name: Jordana Betancourt

[FRONT] Add auth validate if the user is active

---

ram-front/src/__test__/verifySales.test.tsx
ram-front/src/components/forms/ModalGroupForm.tsx
ram-front/src/components/sales/SalesRow.tsx
ram-front/src/components/sales/VerifySalesRow.tsx
ram-front/src/components/sales/VerifySalesTable.tsx
ram-front/src/pages/VerifySales.tsx

**PR Data:**
Task ID: Defect log 94
Problem: When accepting a sale file is not re render in other views
Solution: Add UseEffects
Submitter Name: Jordana Betancourt
Reviewer Name:

326 front 10007 when confirming or rejecting a sale the changes are not reflected in manager view

---

ram-front/src/components/auth/LoginForm.tsx
ram-front/src/components/deliverables/ListDeliverables.tsx
ram-front/src/components/groups/ListGroup.tsx
ram-front/src/containers/Wrapper.tsx
ram-front/src/pages/EditGroup.tsx
ram-front/src/pages/Group.tsx
ram-front/src/pages/Groups.tsx

[FRONT] Changes on Groups and Deliveries

---

ram-back/src/app/user.ts
ram-back/src/entities/user.entity.ts
ram-front/src/components/members/RowMember.tsx

**PR Data:**
Task ID:M4_S01
Problem:isActive is boolean instead of number or interger
Solution: change TYPEORM and other calls in isActive to number
Reviewer Name:

336 back every user that is created has inactive state

---

ram-back/src/controller/assuranceType.ts
ram-back/src/controller/delivery.ts
ram-back/src/controller/group.ts
ram-back/src/controller/sale.ts
ram-back/src/controller/user-delivery.ts
ram-back/src/controller/user.ts

341 fix 82 protect back routes

---

ram-front/src/components/deliverables/UserDeliveriesTable.tsx
ram-front/src/components/deliverables/UserDeliveryRow.tsx
ram-front/src/components/forms/EditDeliveryForm.tsx
ram-front/src/components/forms/ModalGroupForm.tsx
ram-front/src/components/sales/VerifySalesRow.tsx
ram-front/src/pages/EditGroup.tsx
ram-front/src/pages/ManagerDelivery.tsx
ram-front/src/pages/ManagerDeliveryGroup.tsx
ram-front/src/pages/ManagerGroups.tsx

**PR Data:**
Task ID: BUG 100,101 & 63
Problem: When editing a state from group, delivery or user-delivery is not re rendering the information
Solution: Add some useEfects and callbacks, also change some code.
Reviewer Name:
If the submitter makes updates to the PR, you **MUST** go through all …

[FRONT] Fixed re-render bugs

---

ram-back/src/app/user.ts
ram-back/src/controller/user.ts
ram-front/src/components/members/RowMember.tsx
ram-front/src/components/members/TableMembers.tsx
ram-front/src/pages/Members.tsx

**PR Data:**
Task ID: 9050, 9060,9070
Problem: There was no functionality to delete user
Solution: Added a button with delete user functionality in the members view
Reviewer Name:

[FRONT] [BACK] Add delete function for members

---

ram-front/src/components/sales/VerifySalesRow.tsx
ram-front/src/components/sales/VerifySalesTable.tsx

**PR Data:**
Task ID: 106
Problem: The agent who registered it does not appear in each table of sales
Solution: Added  agent name cell in verifySales table
Reviewer Name:

[FRONT] Added cell for agent name in verifySalesTable

---

ram-front/src/components/auth/Login.tsx
ram-front/src/components/auth/LoginForm.tsx

**PR Data:**
Defect Log ID: 111 y 112
Problem: Some elements, such as images, can be selected within the Login
Solution: It was changed that these elements could not be selected, as well as a change in the placeholers
Submitter Name: Alejandro Martínez Luna 
Reviewer Name: Jordana Betancourt Menchaca
If the submitter makes updates to …

[FRONT] Loggin Modified

---

ram-back/src/app/sale.ts
ram-back/src/controller/sale.ts
ram-back/src/seeds/index.ts
ram-front/src/__test__/saleshistory.test.tsx
ram-front/src/components/sales/SalesFilters.tsx
ram-front/src/components/sales/SalesRow.tsx
ram-front/src/components/sales/SalesTable.tsx
ram-front/src/components/sales/VerifySalesRow.tsx
ram-front/src/hooks/useAxios.ts
ram-front/src/hooks/useFilters.ts
ram-front/src/pages/SalesHistory.tsx

Fix filters

---

ram-back/src/app/groups.ts
ram-back/src/controller/group.ts
ram-front/src/components/generics/ProgressBar.tsx
ram-front/src/components/members/RowMember.tsx
ram-front/src/components/metrics/GroupProgress.tsx
ram-front/src/pages/Metrics.tsx
ram-front/src/routes/privates.tsx

**PR Data:**
Task ID: 12050, 12060 & 12060
Problem: There was no view to display metrics
Solution: Added view to display metrics and the metrics for the group progress section
Reviewer Name:

358 front back m4 s02 see progress and metrics in groups of an agent

---

ram-front/src/components/forms/ModalPasswordReset.tsx
ram-front/src/components/forms/SaleForm.tsx
ram-front/src/pages/DeliveryGroup.tsx
ram-front/src/pages/Metrics.tsx

**PR Data:**
Task ID:  BUG 114 & 75
Problem: When an agent has no groups assigned, the page does not load
Solution: Added a conditional when there are no groups of an agent and supporting text
Reviewer Name:

[FRONT] Fixed metrics conditional

---

ram-back/src/app/sale.ts
ram-back/src/controller/sale.ts
ram-back/src/seeds/index.ts
ram-front/src/__test__/verifySales.test.tsx
ram-front/src/components/sales/ManagerSalesFilters.tsx
ram-front/src/components/sales/SalesFilters.tsx
ram-front/src/components/sales/SalesTable.tsx
ram-front/src/components/sales/VerifySalesTable.tsx
ram-front/src/pages/SalesHistory.tsx
ram-front/src/pages/VerifySales.tsx

[FRONT] [BACK] Add filters to sales in manager

---

ram-front/src/components/forms/SaleForm.tsx
ram-front/src/pages/ModifySale.tsx
ram-front/src/pages/NewSale.tsx

[FRONT] Fix form for sale

---

ram-front/src/components/agent/AgentFuzzyFinder.tsx

**PR Data:**
Task ID: BUG 64
Problem: When you add a user to a group it does not confirm that it was added
Solution: Add a sweet alert to confirm that a user was added to a group
Reviewer Name:

[FRONT] Added swal for adding an agent in a group

---

ram-front/src/components/generics/cards/ProfileCard.tsx
ram-front/src/components/includes/NavBar/NavBar.tsx
ram-front/src/components/metrics/ProfileMetrics.tsx
ram-front/src/pages/Metrics.tsx

**PR Data:**
Task ID: 16140
Problem: Add front of profile information to metrics page
Solution: Create a new component
Submitter Name: Fermin
Reviewer Name:

379 front agent resumen information

---

ram-back/src/entities/user.entity.ts
ram-back/src/seeds/index.ts
ram-front/src/components/graphs/LineGraph.tsx
ram-front/src/components/graphs/ProspectChart.tsx
ram-front/src/components/sales/ManagerSalesFilters.tsx
ram-front/src/pages/Examples.tsx
ram-front/src/pages/Metrics.tsx
ram-front/src/pages/ProspectsChart.tsx
ram-front/src/routes/privates.tsx

**PR Data:**
Problem: There was no 
Submitter Name: Alejandro Martínez Luna 
Reviewer Name:

m4 s04 view the lead funnel in graph

---

ram-front/src/components/groups/ListGroup.tsx
ram-front/src/components/groups/ManagerListGroups.tsx
ram-front/src/pages/Groups.tsx

Message when there are no groups modified

---

ram-front/src/pages/Profile.tsx

Hotfix on Profile Edition

---

ram-back/src/controller/status-prospect.ts
ram-front/src/__test__/managerCourses.test.tsx
ram-front/src/components/generics/cards/info/CardInfoNumMembers.tsx
ram-front/src/components/groups/ManagerListGroups.tsx
ram-front/src/pages/ManagerGroups.tsx

Fix Render of deleted group

---

ram-back/src/controller/status-prospect.ts

Modified Endpoint

---

ram-back/src/app/sale.ts

401 fix sales graph

---

ram-front/src/components/metrics/GroupProgress.tsx

**PR Data:**
Task ID: Hot fix for groups metrics
Reviewer Name:

[FRONT] Fixed progress bar bug

---

ram-front/src/pages/Metrics.tsx

**PR Data:**
Task ID: 23000
Problem: In production database paidFee is numeric, which parses as string and generates a highcharts error
Solution: When front end recieves totalPaidFee value its type is a string which is parsed with parseFloat
Submitter Name: Mónica Ayala Marrero.
Reviewer Name:
If the submitter makes updates to the PR, …

[FRONT] Fix numeric parsing as string in Metrics.tsx

---

.env.development
ram-back/src/arch/db-client.ts

**PR Data:**
Task ID: 23200
Problem: Change to PG
Solution: Change to PG
Submitter Name: Angel
Reviewer Name:

[BACK] Change option to PG

---

.env.development
ram-back/src/app/user.ts
ram-back/src/arch/db-client.ts
ram-back/src/arch/s3-client.ts
ram-back/src/entities/columns.ts
ram-back/src/entities/user.entity.ts
ram-back/src/seeds/index.ts

[BACK] Fixed postgres db and seeds

---

ram-back/src/app/deliveries.ts
ram-back/src/entities/columns.ts
ram-front/src/components/generics/cards/ProfileCard.tsx
ram-front/src/components/metrics/ProfileMetrics.tsx
ram-front/src/components/sales/VerifySalesRow.tsx
ram-front/src/pages/DeliveryGroup.tsx

[FRONT] Fixed bugs

---

ram-back/src/controller/status-prospect.ts

**PR Data:**
Problem: There was an error when returning the accumulated number of leads, they were returned as a string
Solution: A controller mod was made to do this conversion
Submitter Name: Alejandro Martínez Luna
Reviewer Name:
If the submitter makes updates …

[BACK] Modified Controller for Prospect Chart

---

ram-back/src/__tests__/app/sale.test.ts
ram-back/src/__tests__/app/user.test.ts
ram-back/src/__tests__/controller/deliveries.test.ts
ram-back/src/__tests__/controller/delivery.test.ts
ram-back/src/__tests__/controller/user.test.ts
ram-back/src/__tests__/infra/arch.test.ts
ram-back/src/app/sale.ts
ram-back/src/arch/db-client.ts
ram-back/src/entities/assurance-type.entity.ts
ram-back/src/entities/columns.ts
ram-back/src/entities/delivery.entity.ts
ram-back/src/entities/sell.entity.ts
ram-back/src/entities/user.entity.ts
ram-back/src/seeds/index.ts
ram-front/src/components/forms/EditDeliveryForm.tsx
ram-front/src/components/prospects/FunnelRow.tsx
ram-front/src/pages/Examples.tsx

[BACK] Fixed uuids

---

ram-back/src/arch/db-client.ts
ram-front/src/components/deliverables/UserDeliveryRow.tsx
ram-front/src/components/includes/Footer/Foot.tsx
ram-front/src/components/sales/VerifySalesRow.tsx

No select on footer

---

ram-back/src/app/sale.ts
ram-back/src/app/user.ts
ram-back/src/controller/user.ts
ram-front/src/components/forms/ProfileForm.tsx
ram-front/src/components/generics/cards/ProfileCard.tsx
ram-front/src/components/graphs/LineGraph.tsx
ram-front/src/components/includes/NavBar/NavBar.tsx
ram-front/src/components/members/RowMember.tsx
ram-front/src/components/members/TableMembers.tsx
ram-front/src/pages/Members.tsx
ram-front/src/pages/Metrics.tsx
ram-front/src/pages/MyManagers.tsx
ram-front/src/pages/ViewManager.tsx
ram-front/src/routes/privates.tsx

416 front members minor fixes
